DROP DATABASE IF EXISTS atletica;
CREATE DATABASE atletica;
USE atletica;

CREATE TABLE ATLETA (
	Matricula INTEGER NOT NULL,
    Nome VARCHAR(30) NOT NULL,
    Curso VARCHAR(20) NOT NULL,
    Genero VARCHAR(10) NULL,
    Imagem blob NULL,
    CHECK (Genero = 'M' OR Genero = 'F'),
    Semestre_Inclusao INTEGER NOT NULL,
    Socio BOOLEAN NOT NULL
);

ALTER TABLE ATLETA
    ADD PRIMARY KEY (Matricula);
    
CREATE TABLE MODALIDADE (
	Nome VARCHAR(30) NOT NULL,
    Genero VARCHAR(10) NOT NULL,
    CHECK (Genero = 'M' OR Genero = 'F'),
    Caixinha VARCHAR(5) NULL
);

ALTER TABLE MODALIDADE
    ADD PRIMARY KEY (Nome,Genero);

CREATE TABLE TECNICO (
	ID_Tecnico INTEGER NOT NULL,
    Nome VARCHAR(30) NULL
);

ALTER TABLE TECNICO
	ADD PRIMARY KEY (ID_Tecnico);
    
CREATE TABLE LUGAR (
	ID_Lugar INTEGER NOT NULL,
    Nome VARCHAR(30) NULL,
    Rua VARCHAR(50) NULL,
    Numero INTEGER NULL
);


ALTER TABLE LUGAR
	ADD PRIMARY KEY(ID_Lugar);
    
CREATE TABLE ATLETA_MODALIDADE (
	Nome_Mod VARCHAR(30) NOT NULL,
    Genero_Mod VARCHAR(10) NOT NULL,
    Matricula_Atl INTEGER NOT NULL,
    Frequencia INTEGER NULL,
    Jogos INTEGER NULL,
    Caixinha_Paga BOOLEAN NOT NULL
);


ALTER TABLE ATLETA_MODALIDADE
	ADD PRIMARY KEY(Nome_Mod,Genero_Mod,Matricula_Atl);
    
ALTER TABLE ATLETA_MODALIDADE
    ADD FOREIGN KEY(Nome_Mod, Genero_Mod)
		REFERENCES MODALIDADE(Nome, Genero);

        
ALTER TABLE ATLETA_MODALIDADE
	ADD FOREIGN KEY(Matricula_Atl)
		REFERENCES ATLETA(Matricula);
        
	-- ADD FOREIGN KEY(Jogos)
	-- 	REFERENCES JOGOS_TREINO(ID_Jogo);
CREATE TABLE JOGOS_TREINO (
	Nome_Mod varchar(30) NOT NULL,
    Genero_Mod VARCHAR(10) NOT NULL,
    ID_Lugar INTEGER NOT NULL,
    Horario TIMESTAMP NULL,
    ID_Jogo INTEGER NOT NULL
);

ALTER TABLE JOGOS_TREINO
	ADD PRIMARY KEY (Nome_Mod,Genero_Mod,ID_Lugar);
    

        
ALTER TABLE JOGOS_TREINO
    ADD FOREIGN KEY(Nome_Mod, Genero_Mod)
		REFERENCES MODALIDADE(Nome, Genero);
        
        
ALTER TABLE JOGOS_TREINO
	ADD FOREIGN KEY (ID_Lugar)
		REFERENCES LUGAR(ID_Lugar);
-- ALTER TABLE JOGOS_TREINO

CREATE TABLE TREINADOR_MOD (
	Nome_Mod varchar(30) NOT NULL,
    Genero_Mod VARCHAR(10) NOT NULL,
    ID_Tecnico INTEGER NOT NULL,
    Salario INTEGER NULL
);

ALTER TABLE TREINADOR_MOD
	ADD PRIMARY KEY (Nome_Mod,Genero_Mod,ID_Tecnico);
    
ALTER TABLE TREINADOR_MOD
	ADD FOREIGN KEY (Nome_Mod,Genero_Mod)
		REFERENCES MODALIDADE(Nome,Genero);
        

ALTER TABLE TREINADOR_MOD
	ADD FOREIGN KEY (ID_Tecnico)
		REFERENCES TECNICO(ID_Tecnico);
        
        
CREATE TABLE STAT (
	Matricula INTEGER NOT NULL,
    ID_Jogo INTEGER NOT NULL,
    Pesenca INTEGER NULL
);

ALTER TABLE STAT
	ADD PRIMARY KEY(Matricula,ID_Jogo);
    
ALTER TABLE STAT
	ADD FOREIGN KEY (Matricula)
		REFERENCES ATLETA(Matricula);
        
-- ALTER TABLE STAT
-- 	ADD FOREIGN KEY (ID_Jogo)
-- 		REFERENCES JOGOS_TREINO(ID_Jogo);

